package stairwaytoheaven.items;

import necesse.engine.localization.message.GameMessage;
import necesse.engine.localization.message.LocalMessage;
import necesse.engine.registries.ObjectRegistry;
import necesse.engine.util.GameBlackboard;
import necesse.entity.mobs.PlayerMob;
import necesse.gfx.gameTexture.GameTexture;
import necesse.gfx.gameTooltips.ListGameTooltips;
import necesse.inventory.InventoryItem;
import necesse.inventory.item.placeableItem.objectItem.ObjectItem;

/**
 * Ghost Chalk — one piece, one Séance Circle, and then it is gone.
 *
 * <h2>What it is in engine terms</h2>
 *
 * A {@link ObjectItem}, vanilla's own placeable-object item, pointed at the
 * {@code seancecircle} object rather than at one named after itself. That is
 * the whole implementation: {@code ObjectItem}'s constructor is
 * {@code super(object.stackSize, true)} and the {@code true} is
 * {@code PlaceableItem.singleUse}, so {@code ObjectItem.onPlace} ends with
 * {@code item.setAmount(item.getAmount() - 1)} (ObjectItem.java:344-345,
 * VERIFIED [jar]). <b>The chalk is consumed by drawing the circle</b> without a
 * line of code here saying so.
 *
 * <h2>Why the chalk and not the circle is the item</h2>
 *
 * {@code docs/FOGKEY_AND_BOSSPORTALS.md} A1/A2: the chalk is what the Warden
 * hands over and restocks, and the circle is "placed from {@code ghostchalk};
 * the chalk is consumed". So {@code seancecircle} is registered
 * <b>unobtainable</b> — it grows no item of its own — and this is the only
 * thing in the game that puts one on the ground. Mining a placed circle gives
 * the chalk back ({@code SeanceCircleObject.getLootTable}), so the loop is
 * closed with exactly one item in it instead of two that do the same job.
 *
 * <h2>Two overrides, and why each is needed</h2>
 *
 * <ul>
 *   <li>{@link #getNewLocalization()} — {@code ObjectItem} returns the OBJECT's
 *       name (ObjectItem.java:76), which would put "Seance Circle" on the chalk
 *       in the inventory and in the Warden's shop. This puts it back on
 *       {@code item.ghostchalk}, which is what {@code Item} does for everything
 *       else.</li>
 *   <li>{@link #loadItemTextures()} — {@code ObjectItem} draws
 *       {@code this.getObject().generateItemTexture()}, i.e.
 *       {@code items/seancecircle.png}. That is in fact the right picture (a
 *       chalk ring is what the chalk makes), but it has to be said out loud
 *       rather than inherited, because the icon file is a constructor argument
 *       here and {@code tools/locale_audit.py} reads that argument to check the
 *       file exists. <b>No new art:</b> the sheet is the mod's own, already
 *       generated by {@code tools/asset_generator/gen_veil.py:gen_seancecircle},
 *       and the borrow is written down in
 *       {@code docs/VANILLA_ASSET_MAP.md} §1.6.</li>
 * </ul>
 */
public class GhostChalkItem extends ObjectItem {

    /** File under {@code items/}, without the extension. */
    private final String iconName;

    /**
     * @param iconName file under {@code items/} to draw, WITHOUT the extension
     * @param objectID the registered object this chalk places
     */
    public GhostChalkItem(String iconName, int objectID) {
        super(ObjectRegistry.getObject(objectID));
        this.iconName = iconName;
        // A key, not a building material: the same place the Silver Bell sits
        // (SkyBuildingSet.registerItems) and where vanilla files all 32 of its
        // own quest items (QuestItem.java:29, category created by the engine at
        // ItemCategory.java:286). ObjectItem's constructor copied the object's
        // objects/misc category in; this replaces it.
        this.setItemCategory("misc", "questitems");
        // Ten, matching silverbell's stack. It is not a resource you hoard.
        this.stackSize = 10;
    }

    /**
     * The chalk's own name, not the circle's.
     *
     * <p>{@code Item.getNewLocalization} resolves the {@code item} section by
     * the item's own string ID; {@code ObjectItem} overrides it to the object's
     * name, which is the one thing about being an ObjectItem that is wrong
     * here.
     */
    @Override
    public GameMessage getNewLocalization() {
        return new LocalMessage("item", this.getStringID());
    }

    @Override
    public void loadItemTextures() {
        this.itemTexture = GameTexture.fromFile("items/" + this.iconName);
    }

    /**
     * The description line, on top of the object tooltip {@code ObjectItem}
     * already adds. {@link ItemDescription} is the mod's own resolver for
     * {@code itemtooltip.<stringID>tip} — it returns null rather than printing
     * the raw key when the entry is missing, and its presence in this class is
     * what makes {@code tools/locale_audit.py} demand the line in both locales.
     */
    @Override
    public ListGameTooltips getTooltips(InventoryItem item, PlayerMob perspective, GameBlackboard blackboard) {
        ListGameTooltips tooltips = super.getTooltips(item, perspective, blackboard);
        String line = ItemDescription.of(this.getStringID());
        if (line != null) {
            tooltips.add(line);
        }
        return tooltips;
    }
}
