#!/usr/bin/env bash
# Fresh install into an EXISTING world — the check the integration test cannot make.
#
# scripts/integration_test.sh always CREATES its world, so every part of the mod
# it exercises was generated by a server that already had the mod. That proves
# nothing about the case the player actually has: a world played for weeks with
# vanilla and three other mods, into which Stairway to Heaven is dropped for the
# first time. docs/SAVE_COMPAT.md §7 is what this script tests.
#
# It boots the real 1.3.3 server on a COPY of a real save, with the same mod set
# the player has, and drives the mod's status commands over the console. The
# copy is made here; the script never touches a save directory.
#
# Requirements:
#   - NECESSE_GAME_DIR points at an install with Server.jar (Steam works, and is
#     the right one: the save was written by 1.3.3 and the jar targets 1.3.3)
#   - the mod jar was built: ./gradlew buildModJar
#
# Usage: scripts/save_compat_check.sh <world.zip> [extra-mods-dir]
#
#   world.zip        a COPY of a real world, e.g. from backup-saves-<date>/
#   extra-mods-dir   the other mods the world was played with; each *.jar in it
#                    is loaded beside ours, so unknown-object warnings from a
#                    missing third-party mod cannot be mistaken for our bug

set -u
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
GAME_DIR="${NECESSE_GAME_DIR:?Set NECESSE_GAME_DIR to an install containing Server.jar}"
WORLD_ZIP="${1:?Usage: scripts/save_compat_check.sh <world.zip> [extra-mods-dir]}"
EXTRA_MODS="${2:-}"

MOD_JAR="$(ls "$REPO_DIR"/build/jar/*.jar 2>/dev/null | head -1)"
[ -n "$MOD_JAR" ] || { echo "FAIL: no mod jar in build/jar (run ./gradlew buildModJar)"; exit 1; }
[ -f "$WORLD_ZIP" ] || { echo "FAIL: no such world zip: $WORLD_ZIP"; exit 1; }

WORK_DIR="${SAVE_COMPAT_WORK_DIR:-$REPO_DIR/build/save-compat-$$}"
PORT="${SAVE_COMPAT_PORT:-$(( 17000 + $$ % 2000 ))}"
WORLD="$(basename "$WORLD_ZIP" .zip)"

# Steam ships a WINDOWS jre/; only the dedicated-server download has a usable
# one. Fall back to PATH java, which is what runs this under WSL.
JAVA_BIN="$GAME_DIR/jre/bin/java"
[ -x "$JAVA_BIN" ] || JAVA_BIN="java"

rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR/saves/worlds" "$WORK_DIR/mods"
# A COPY, always. The point of this script is to be safe to run against the
# player's real save, and it can only claim that if it never opens the original.
cp "$WORLD_ZIP" "$WORK_DIR/saves/worlds/"
cp "$MOD_JAR" "$WORK_DIR/mods/"
if [ -n "$EXTRA_MODS" ] && [ -d "$EXTRA_MODS" ]; then
    for jar in "$EXTRA_MODS"/*.jar; do
        [ -e "$jar" ] && cp "$jar" "$WORK_DIR/mods/"
    done
fi

LOG="$WORK_DIR/server.log"
SERVER_PID=""
PIPE="$WORK_DIR/cmd.pipe"

fail() {
    echo "FAIL: $1"
    echo "--- last 40 log lines ---"
    tail -40 "$LOG" 2>/dev/null || true
    [ -n "$SERVER_PID" ] && kill "$SERVER_PID" 2>/dev/null
    exit 1
}

wait_for() { # pattern timeout_seconds
    local pattern="$1" timeout="$2" waited=0
    while ! grep -qE "$pattern" "$LOG" 2>/dev/null; do
        sleep 1
        waited=$((waited + 1))
        kill -0 "$SERVER_PID" 2>/dev/null || fail "server exited early while waiting for: $pattern"
        [ "$waited" -ge "$timeout" ] && fail "timeout waiting for: $pattern"
    done
}

cd "$WORK_DIR"
rm -f "$PIPE"
mkfifo "$PIPE"
unset JAVA_TOOL_OPTIONS
echo "Booting 1.3.3 server on a COPY of $WORLD (port $PORT), mods: $(ls mods | tr '\n' ' ')"
"$JAVA_BIN" -Xms256m -Xmx2G -Djdk.attach.allowAttachSelf=true -jar "$GAME_DIR/Server.jar" -nogui -localdir \
    -world "$WORLD" -owner tester -port "$PORT" -mod "\"$WORK_DIR/mods\"" \
    < "$PIPE" > "$LOG" 2>&1 &
SERVER_PID=$!
exec 3> "$PIPE"

wait_for "Loaded mods:|Stairway to Heaven" 180
# "loaded" and not "created": the world existed before this run. An existing
# world reports its levels being READ; a fresh one reports generation.
wait_for "Type help for list of commands|Server started" 300
sleep 5

# The Skyreach does not exist in this save. Asking for its status is what the
# Skyward Stairway's use() does one call deeper: WorldGenerator hands out a new
# SkyLevel, which is the whole question this script asks.
echo "Asking for the Skyreach (it has never existed in this world)..."
echo "skyreachstatus" >&3
wait_for "SKYREACH_STATUS_DONE" 300

# Second pass: serverTick has now stamped the spire and spawned the cats.
sleep 8
echo "skyreachstatus" >&3
for _ in $(seq 1 90); do
    [ "$(grep -c SKYREACH_STATUS_DONE "$LOG")" -ge 2 ] && break
    sleep 2
done

# The report-only form. On a world that has never had the mod it should say the
# story has not started -- and say it without touching anything.
echo "Reporting what this world holds (/swhreset, report only)..."
echo "swhreset" >&3
sleep 8

echo "Saving..."
echo "save" >&3
waited=0
while [ "$(grep -c "Completed world save" "$LOG" 2>/dev/null || true)" -lt 1 ]; do
    sleep 1
    waited=$((waited + 1))
    kill -0 "$SERVER_PID" 2>/dev/null || fail "server exited while saving"
    [ "$waited" -ge 300 ] && fail "timeout waiting for the world save"
done
echo "stop" >&3
for _ in $(seq 1 60); do
    kill -0 "$SERVER_PID" 2>/dev/null || break
    sleep 1
done
kill "$SERVER_PID" 2>/dev/null
exec 3>&-

echo
echo "=== result ==="
grep -E "class=SkyLevel|identifier=skyreach2" "$LOG" | head -3
FAILS=0
grep -qE "class=SkyLevel" "$LOG" || { echo "FAIL: the Skyreach never came up"; FAILS=1; }
# Our own package must not appear in a stack trace. Other mods' warnings are
# not ours to fix and are reported rather than failed on.
if grep -qE "stairwaytoheaven.*(Exception|Error)|at stairwaytoheaven\." "$LOG"; then
    echo "FAIL: the mod appears in an exception:"
    grep -nE "stairwaytoheaven.*(Exception|Error)|at stairwaytoheaven\." "$LOG" | head -10
    FAILS=1
fi
echo "log: $LOG"
[ "$FAILS" -eq 0 ] && echo "OK: the mod loaded into an existing world and the Skyreach came up"
exit "$FAILS"
