#!/usr/bin/env python3
"""Labelled drawing templates, one per asset class.

The wall template (tools/wall_template_map.py) exists because the renderer's
grammar is invisible from an image editor. Every other class has the same
problem in a smaller way: a mob sheet's rows are Up/Right/Down/Left and not
the order anyone guesses, a splat's 21 cells each have a required alpha shape,
an object is bottom-anchored except when it is top-anchored. So each class gets
the same treatment: a canvas at the exact shipped size, every cell labelled
with what goes in it, and the rules written next to it.

These are drawing guides AND generator prompts -- hand the PNG to an image
model together with the brief from `docs/ASSET_PIPELINE.md` and it composes
into the right cells instead of into a nice picture that the engine then
shreds.

    python3 tools/asset_templates.py                  # all classes
    python3 tools/asset_templates.py --class mob      # one
    python3 tools/asset_templates.py --list

Writes build/qa/template-<class>.png and copies them to docs/references/.

Every dimension and cell meaning below is cited to the file it was verified
in; nothing here is asserted from memory. The wall class is not duplicated --
it is generated by wall_template_map.py, which derives its cell roles by
enumerating the engine port.
"""
import argparse
import os

from PIL import Image, ImageDraw, ImageFont

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_QA = os.path.join(REPO, "build", "qa")
OUT_DOCS = os.path.join(REPO, "docs", "references")

BG = (24, 24, 30, 255)
GRID = (255, 255, 255, 90)
CO_A = (60, 160, 255)
CO_B = (255, 170, 60)
CO_C = (120, 235, 205)
CO_D = (200, 70, 220)
CO_WARN = (235, 60, 60)


def fonts():
    try:
        return (ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 14),
                ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 12),
                ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf", 18))
    except OSError:
        f = ImageFont.load_default()
        return f, f, f


def canvas(art_w, art_h, legend_w, text_h, zoom, reference=None):
    """Checkerboard art area + legend column + rules strip."""
    img = Image.new("RGBA", (art_w * zoom + legend_w, art_h * zoom + text_h), BG)
    checker = Image.new("RGBA", (art_w * zoom, art_h * zoom), (46, 46, 56, 255))
    cd = ImageDraw.Draw(checker)
    for y in range(0, art_h * zoom, 16):
        for x in range(0, art_w * zoom, 16):
            if ((x + y) // 16) % 2 == 0:
                cd.rectangle((x, y, x + 15, y + 15), fill=(58, 58, 70, 255))
    img.alpha_composite(checker, (0, 0))
    if reference is not None and os.path.exists(reference):
        ref = Image.open(reference).convert("RGBA")
        if ref.size == (art_w, art_h):
            img.alpha_composite(ref.resize((art_w * zoom, art_h * zoom), Image.NEAREST), (0, 0))
    return img


def tint(img, box, colour, alpha=52):
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    ImageDraw.Draw(layer).rectangle(box, fill=colour + (alpha,))
    img.alpha_composite(layer)


def write_block(d, x, y, lines, font, colour=(225, 225, 230), step=20):
    for line in lines:
        d.text((x, y), line, fill=colour, font=font)
        y += step
    return y


def finish(img, d, title, legend, rules, art_w, art_h, zoom, font, font_big):
    lx = art_w * zoom + 16
    d.text((lx, 10), title, fill=(255, 255, 255), font=font_big)
    write_block(d, lx, 40, legend, font)
    write_block(d, 14, art_h * zoom + 12, rules, font)


# ---------------------------------------------------------------------------
# mob: walking, 4-direction

def template_mob(cell=64):
    """6 cols x 4 rows of `cell`, then a 32px GIB STRIP, then 32px of padding.

    Rows are Up/Right/Down/Left -- VERIFIED in docs/research/asset-formats.md 5,
    resolved there from the Mob class rather than from the wiki, which had it
    wrong.

    The gib strip is not folklore either: mobs spawn death chunks with
    `new FleshParticle(level, texture, spriteX, 8, 32, ...)` -- sprite column
    spriteX, ROW 8 in 32px units (y256..288), 32px cells, spriteX drawn from
    `nextInt(5)` or a `for i < 4` loop. VERIFIED [jar] in CrystalGolemMob,
    BloatedSpiderMob, ChickenRaiderMob, AncientSkeletonRaiderMob.

    Measured on vanilla crystalgolem, bloatedspider and our own crookedgolem:
    all three are 384x320, all three fill y256..288 in the first 3-4 columns
    only, and all three leave y288..320 completely empty.
    """
    zoom = 3
    art_w, art_h = cell * 6, cell * 4 + 64
    ref = os.path.join(REPO, "src/main/resources/mobs/crookedgolem.png")
    have_ref = os.path.exists(ref) and Image.open(ref).size == (art_w, art_h)
    img = canvas(art_w, art_h, 660, 300, zoom, ref if have_ref else None)
    d = ImageDraw.Draw(img)
    font, font_sm, font_big = fonts()
    cols = ("idle", "walk 1", "walk 2", "walk 3", "walk 4", "in liquid")
    rows = ("UP\n(back)", "RIGHT\n(side)", "DOWN\n(front)", "LEFT\n(side)")
    for r in range(4):
        for c in range(6):
            x0, y0 = c * cell * zoom, r * cell * zoom
            box = (x0, y0, x0 + cell * zoom - 1, y0 + cell * zoom - 1)
            tint(img, box, CO_A if c in (0, 5) else CO_B, 40)
            d.rectangle(box, outline=GRID)
            d.text((x0 + 6, y0 + 4), cols[c], fill=(255, 255, 255), font=font)
            yy = y0 + 24
            for line in rows[r].split("\n"):
                d.text((x0 + 6, yy), line, fill=(235, 235, 240), font=font_sm)
                yy += 14
            d.text((x0 + 6, y0 + cell * zoom - 20), "%dx%d" % (cell, cell),
                   fill=(190, 190, 200), font=font_sm)
    d.rectangle((5 * cell * zoom, 0, 6 * cell * zoom - 1, 4 * cell * zoom - 1),
                outline=CO_C, width=3)
    # the gib strip and the padding row, both in 32px units
    gy = 4 * cell * zoom
    for c in range(12):
        x0 = c * 32 * zoom
        box = (x0, gy, x0 + 32 * zoom - 1, gy + 32 * zoom - 1)
        if c < 5:
            tint(img, box, CO_D, 60)
            d.text((x0 + 4, gy + 4), "gib %d" % c, fill=(255, 225, 255), font=font_sm)
        d.rectangle(box, outline=GRID)
    d.rectangle((0, gy, 5 * 32 * zoom - 1, gy + 32 * zoom - 1), outline=CO_D, width=3)
    d.text((5 * 32 * zoom + 8, gy + 6), "DEATH CHUNKS: 32px cells, up to 5 of them",
           fill=(255, 200, 255), font=font)
    d.text((5 * 32 * zoom + 8, gy + 26), "(FleshParticle reads sprite row 8)",
           fill=(255, 200, 255), font=font_sm)
    py = gy + 32 * zoom
    d.rectangle((0, py, art_w * zoom - 1, art_h * zoom - 1), outline=(140, 140, 150), width=2)
    d.text((8, py + 8), "unused padding - vanilla leaves this row empty",
           fill=(190, 190, 200), font=font)

    legend = ["Cell %dpx. 6 columns x 4 rows," % cell,
              "then a 32px gib strip, then padding.",
              "",
              "col  0     idle / standing",
              "cols 1-4   the walk cycle, in order",
              "col  5     drawn while in liquid (cyan):",
              "           same pose, lower body cut off",
              "           at the surface line",
              "",
              "rows       UP, RIGHT, DOWN, LEFT - in THAT",
              "           order. Not compass order.",
              "",
              "y256-288   death chunks, 32px cells",
              "y288-320   unused, leave empty",
              "",
              "LEFT is not a free mirror of RIGHT: the",
              "engine does not flip. Draw it, or paste",
              "RIGHT mirrored and redo the shading -",
              "light always comes from the top-left.",
              "",
              "Optional companions, same grid:",
              "  mobs/<id>_light.png    glow pass",
              "  mobs/<id>_shadow.png   4 cols x 1 row",
              "  mobs/icons/<id>.png    32x32 bestiary"]
    rules = ["ANCHORING: feet near the bottom of the cell, sprite centred horizontally.",
             "Match the mass of a vanilla mob of the same role -- tools/size_audit.py compares you against one and a",
             "FIX flag blocks shipping. Necesse mobs are CHUNKY: big head, silhouette readable at 1x.",
             "",
             "Background fully transparent. Soft dark outline (34,34,46) around the body, never pure black."]
    if have_ref:
        rules.append("The art behind this template is our own crookedgolem sheet, for mass and framing reference.")
    finish(img, d, "MOB SHEET (walking, 4-dir)  %dx%d" % (art_w, art_h),
           legend, rules, art_w, art_h, zoom, font, font_big)
    return img, "mob"


# ---------------------------------------------------------------------------
# tile: the _splat atlas

def template_splat(variants=4):
    """224 x 96*variants. Cell map VERIFIED in docs/research/splat-format.md 5.3,
    which was cross-checked against dirt/snow/ash _splat by per-cell alpha."""
    zoom = 4
    art_w, art_h = 224, 96 * variants
    img = canvas(art_w, art_h, 700, 480, zoom,
                 os.path.join(REPO, "src/main/resources/tiles/cloudturf_splat.png"))
    d = ImageDraw.Draw(img)
    font, font_sm, font_big = fonts()
    # (col,row) -> (short, long)
    CELLS = {
        (3, 0): ("FULL 1", "plain tile\n+ ITEM ICON"), (4, 0): ("FULL 2", "plain tile"),
        (5, 0): ("FULL 3", "plain tile"), (6, 0): ("FULL 4", "plain tile"),
        (1, 1): ("all 4", "opaque\nall edges"),
        (1, 0): ("S", "opaque\nBOTTOM"), (1, 2): ("N", "opaque\nTOP"),
        (2, 1): ("W", "opaque\nLEFT"), (0, 1): ("E", "opaque\nRIGHT"),
        (3, 1): ("N+W", "cut SE\nquadrant"), (4, 1): ("N+E", "cut SW"),
        (3, 2): ("S+W", "cut NE"), (4, 2): ("E+S", "cut NW"),
        (5, 1): ("N+E+W", "thin at\nbottom"), (6, 1): ("N+E+S", "thin at\nleft"),
        (5, 2): ("E+S+W", "thin at\ntop"), (6, 2): ("N+S+W", "thin at\nright"),
        (0, 0): ("diag SE", "blob, notch\nat NW"), (2, 0): ("diag SW", "blob, notch\nat NE"),
        (0, 2): ("diag NE", "blob, notch\nat SW"), (2, 2): ("diag NW", "blob, notch\nat SE"),
    }
    for v in range(variants):
        oy = v * 96 * zoom
        for (cx, cy), (short, long) in CELLS.items():
            x0, y0 = cx * 32 * zoom, oy + cy * 32 * zoom
            box = (x0, y0, x0 + 32 * zoom - 1, y0 + 32 * zoom - 1)
            tint(img, box, CO_C if cx >= 3 and cy == 0 else CO_A, 46)
            d.rectangle(box, outline=GRID)
            if v == 0:
                d.text((x0 + 4, y0 + 3), short, fill=(255, 255, 255), font=font)
                yy = y0 + 22
                for line in long.split("\n"):
                    d.text((x0 + 4, yy), line, fill=(235, 235, 240), font=font_sm)
                    yy += 14
        d.rectangle((0, oy, art_w * zoom - 1, oy + 96 * zoom - 1),
                    outline=CO_D, width=3)
        d.text((6, oy + 96 * zoom - 22), "variant %d (whole 224x96 block)" % v,
               fill=(255, 200, 255), font=font)
    finish(img, d, "TERRAIN _splat ATLAS  224 x 96*variants",
           ["7x3 cells of 32px = one 224x96 BLOCK.",
            "Stack one block per variant, downward.",
            "Shipped grounds use 5-6 variants.",
            "",
            "The four cyan FULL cells are the tile you",
            "actually see most of the time. (3,0) is",
            "ALSO the item icon the game generates.",
            "",
            "Every other cell is a BLEND piece: the",
            "same material, with alpha cut to the shape",
            "named in it, so this ground fades into the",
            "one beside it.",
            "",
            "N/E/S/W in a cell name = which neighbours",
            "are the same ground; the OPAQUE part faces",
            "those neighbours.",
            "",
            "Liquids need this too (224*frames wide)."],
           ["THE TWO RULES THAT DECIDE WHETHER IT LOOKS VANILLA (tools/tile_behaviour_audit.py enforces both):",
            "1. The tone unit is a 2x2 PIXEL BLOCK, never a lone pixel. Vanilla is 100% coherent on that grid.",
            "2. Texture comes from MANY QUIET steps, not few loud ones: mean |dRGB| from the modal colour 7-27,",
            "   density 280-620 non-modal px per 32x32 cell. Vanilla carries a whole grass texture in five RGB levels.",
            "",
            "Draw ONE seamless 32x32 material first. Everything else is that material with alpha cut to shape."],
           art_w, art_h, zoom, font, font_big)
    return img, "splat"


# ---------------------------------------------------------------------------
# object + item

def template_object():
    """32*cols x 32*rows, bottom-anchored in the sorted layer. VERIFIED in
    docs/research/asset-formats.md 3 and its summary table."""
    zoom = 4
    art_w, art_h = 32 * 4, 32 * 4
    img = canvas(art_w, art_h, 700, 460, zoom)
    d = ImageDraw.Draw(img)
    font, font_sm, font_big = fonts()
    for c in range(4):
        x0 = c * 32 * zoom
        d.rectangle((x0, 0, x0 + 32 * zoom - 1, art_h * zoom - 1), outline=CO_B, width=3)
        d.text((x0 + 6, 6), "variant %d" % c, fill=(255, 220, 170), font=font)
    for r in range(4):
        y0 = r * 32 * zoom
        d.rectangle((0, y0, art_w * zoom - 1, y0 + 32 * zoom - 1), outline=GRID)
        d.text((6, y0 + 32 * zoom - 20),
               "row %d  (%s)" % (r, "the object's OWN tile" if r == 3
                                 else "%d tile(s) of height above it" % (3 - r)),
               fill=(235, 235, 240), font=font_sm)
    d.rectangle((0, 3 * 32 * zoom, art_w * zoom - 1, art_h * zoom - 1),
                outline=CO_C, width=4)
    finish(img, d, "OBJECT SHEET  32*variants wide x 32*N tall",
           ["Width  = 32 x however many random variants",
            "Height = 32 x how tall the thing is",
            "",
            "BOTTOM-ANCHORED (sorted layer): the LAST",
            "32px row is the tile the object stands on",
            "(cyan). Everything above it rises into the",
            "tiles behind, drawn in front of them.",
            "",
            "Top-anchored instead (tile-decal layer)",
            "for flat things -- carpets, floor marks.",
            "",
            "Shipped examples, all real sizes:",
            "  items/skyreave.png        32x32",
            "  objects/skyanchor.png     32x64",
            "  objects/statues/...       64x96",
            "  objects/mistglasslantern  64x128",
            "  objects/wardencandelabra  32x192",
            "",
            "A holdable object ALSO needs a 32x32",
            "icon at items/<id>.png."],
           ["VARIANTS ARE NOT OPTIONAL DECORATION. A ground scattered with one silhouette reads as a grid of",
            "stamps. Vanilla ships 4-8 variants for anything common; 2 is the floor for anything rare.",
            "",
            "Light from the TOP-LEFT, 2-4 flat shade steps, soft dark outline (34,34,46) -- never pure black.",
            "Silhouette has to read at 1x against BOTH a light ground (cloudturf) and a dark one (stormslate)."],
           art_w, art_h, zoom, font, font_big)
    return img, "object"


def template_item():
    """32x32 icon. Summary table: "items/<stringid>.png, 32x32 recommended"."""
    zoom = 10
    art_w = art_h = 32
    img = canvas(art_w, art_h, 700, 420, zoom)
    d = ImageDraw.Draw(img)
    font, font_sm, font_big = fonts()
    for i in range(0, 33, 4):
        d.line((i * zoom, 0, i * zoom, art_h * zoom), fill=(255, 255, 255, 40))
        d.line((0, i * zoom, art_w * zoom, i * zoom), fill=(255, 255, 255, 40))
    # the safe area vanilla icons keep to
    d.rectangle((2 * zoom, 2 * zoom, 30 * zoom - 1, 30 * zoom - 1), outline=CO_C, width=3)
    d.text((2 * zoom + 6, 2 * zoom + 4), "keep inside: 28x28", fill=(190, 245, 230), font=font)
    d.rectangle((6 * zoom, 2 * zoom, 26 * zoom - 1, 30 * zoom - 1), outline=CO_B, width=2)
    d.text((6 * zoom + 6, 30 * zoom - 24), "tools sit in this 20x28", fill=(255, 220, 170), font=font_sm)
    finish(img, d, "ITEM ICON  32x32",
           ["One object, centred, filling the frame.",
            "",
            "Vanilla icons are NOT shrunken world",
            "sprites -- they are drawn for the slot:",
            "a tree's icon is a compact glyph, not the",
            "128x1024 world sheet scaled down.",
            "",
            "Cyan  28x28 safe area (2px margin all",
            "      round so the UI's hover ring and",
            "      the stack count do not clip it).",
            "Amber the narrower box tools/weapons use:",
            "      they read as a diagonal from the",
            "      bottom-left to the top-right.",
            "",
            "Straight alpha. No drop shadow, no glow,",
            "no background plate."],
           ["Every holdable thing needs one, or it shows the pink ERROR texture in the inventory.",
            "tools/locale_audit.py fails the build when a registered holdable ID has no items/<id>.png.",
            "",
            "Same palette discipline as the world sprite: light top-left, 2-4 flat steps, soft dark outline."],
           art_w, art_h, zoom, font, font_big)
    return img, "item"


BUILDERS = {
    "mob": template_mob,
    "splat": template_splat,
    "object": template_object,
    "item": template_item,
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--class", dest="klass", default=None,
                    help="one of: " + ", ".join(sorted(BUILDERS)) + " (default: all)")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()
    if args.list:
        print("classes:", ", ".join(sorted(BUILDERS)))
        print("wall: generated by tools/wall_template_map.py (roles enumerated "
              "from the engine port)")
        return
    names = [args.klass] if args.klass else sorted(BUILDERS)
    os.makedirs(OUT_QA, exist_ok=True)
    os.makedirs(OUT_DOCS, exist_ok=True)
    for name in names:
        if name not in BUILDERS:
            raise SystemExit("unknown class %r; --list to see them" % name)
        img, slug = BUILDERS[name]()
        p = os.path.join(OUT_QA, "template-%s.png" % slug)
        img.save(p)
        img.save(os.path.join(OUT_DOCS, "template-%s.png" % slug))
        print("wrote %s  %s" % (p, img.size))


if __name__ == "__main__":
    main()
